### ISSUE TITLE
Small fixes

### ISSUE THREAD

**Issue by arkim989** [npranto/logtrade#77]
1 Stop loss and take profit should be optional

2 prices on add trade should not start from 0.00, when clicked to write the price, cursor should be at the beginning so you don’t have to erase 0.00

3 when adding a new trade, at the end should be another button to "add another trade" so that you don’t have to create it and than click again on that day to add second, 3rd, 4th trade.

**Comment by npranto** [comment]
@arkim989 all 3 features/bugs above ^ have been fixed on https://dev-logtrade.netlify.app/home/ in case you want to check it out. We'll release these features on production w/ v2.0.0 later in the next couple of weeks or so.
